service:
  serviceName: time-service
  serviceId: ts-2
  ipAddress: "172.16.0.7"
  port: 28281
  heartbeatInterval: 30

registry:
  addresses:
    - http://172.16.0.7:28180
    - http://172.16.0.7:28181
